### ISSUE TITLE
Change the behavior of the spark_binary connection option in the spark_submit hook

### ISSUE THREAD

**Issue by seyoon-lim** [kakao-hunters/airflow#2]
### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by softyoungha** [comment]
gd

**Comment by seyoon-lim** [comment]
@softyoungha 
parameter로 넘기는 값과 connection으로 넘기는 값의 validation이 다른게 문제가 된다고 생각해서 논의했던 대로 이슈라이징 했습니당 

요기서 피드백 받고 구현 단계로 넘어가면 요 이슈 해결하는 PR로 가겠습니당

**Comment by seyoon-lim** [comment]
@softyoungha 
potiuk이 설명해주시길 connection이 execution에 극히 제한된 영역만 담당하게 하려는 것 같네요

생각해보니까 spark_binary 값을 그대로 subprocess로 cmd 콜때리는데 되게 위험한 feature긴 하네여

airflow 이슈 따라서 요거도 close 처리합니당
